name: nf-jdk nighly build
on:
  schedule:
    - cron: "0 1 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  build-backend:
    name: nf-jdk nightly build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Docker Login 
      uses: docker/login-action@v2
      with:
        registry: "cr.seqera.io"
        username: ${{ secrets.SEQERA_CR_USERNAME }}
        password: ${{ secrets.SEQERA_CR_PASSWORD }}

    - name: Build image
      run: make all version=$(cat VERSION_NIGHTLYBUILD)

