ARG VERSION

FROM public.ecr.aws/amazoncorretto/amazoncorretto:$VERSION

## see https://technology.blog.gov.uk/2015/12/11/using-jemalloc-to-get-to-the-bottom-of-a-memory-leak/
# Copy installation scripts
ADD install-jemalloc.sh wait-for-it.sh /usr/local/bin/

# Install jemalloc and required packages in single layer
RUN yum update -y && \
    yum install -y tar gzip procps which && \
    bash /usr/local/bin/install-jemalloc.sh && \
    yum clean all && \
    rm -f /usr/local/bin/install-jemalloc.sh

# Set environment to use jemalloc
ENV LD_PRELOAD=/usr/lib64/libjemalloc.so.2

