FROM amazoncorretto:11.0.9 AS builder

RUN yum update -y && yum install -y tar gzip
RUN curl -L https://github.com/patric-r/jvmtop/releases/download/0.8.0/jvmtop-0.8.0.tar.gz | tar xz \
 && chmod +x jvmtop.sh \
 && mv jvmtop.jar /usr/local/bin/ \
 && mv jvmtop.sh /usr/local/bin/jvmtop

FROM amazoncorretto:11.0.9
COPY --from=builder /usr/local/bin/jvmtop /usr/local/bin/jvmtop
COPY --from=builder /usr/local/bin/jvmtop.jar /usr/local/bin/jvmtop.jar
