ARG VERSION
ARG TARGETARCH

FROM public.ecr.aws/amazoncorretto/amazoncorretto:$VERSION

## see https://technology.blog.gov.uk/2015/12/11/using-jemalloc-to-get-to-the-bottom-of-a-memory-leak/
ADD jemalloc-binaries/${TARGETARCH} /opt/jemalloc

# Install file command and debug: verify jemalloc files are copied correctly
RUN yum install -y file && \
    echo "=== DEBUG: Checking jemalloc installation ===" && \
    ls -la /opt/jemalloc/ && \
    echo "=== /opt/jemalloc/lib/ contents ===" && \
    ls -la /opt/jemalloc/lib/ && \
    echo "=== File info for libjemalloc.so.2 ===" && \
    file /opt/jemalloc/lib/libjemalloc.so.2 && \
    echo "=== Architecture info ===" && \
    uname -m

ENV \
  PATH=$PATH:/opt/jemalloc/bin \
  LD_PRELOAD=/opt/jemalloc/lib/libjemalloc.so.2

ADD wait-for-it.sh /usr/local/bin/

RUN yum update -y \
    && yum install -y tar gzip procps which \
    && yum clean all

