name: Build mimalloc binaries
on:
  push:
    branches:
      - '*'
    paths:
      - 'build-mimalloc-native.sh'
      - '.github/workflows/build-mimalloc.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-mimalloc-amd64:
    name: Build mimalloc for AMD64
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl cmake
        
    - name: Build mimalloc for AMD64
      run: ./build-mimalloc-native.sh amd64
      
    - name: Upload AMD64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mimalloc-amd64
        path: mimalloc-binaries/amd64/
        retention-days: 1

  build-mimalloc-arm64:
    name: Build mimalloc for ARM64
    runs-on: ubuntu-24.04-arm64
    timeout-minutes: 20
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl cmake
        
    - name: Build mimalloc for ARM64
      run: ./build-mimalloc-native.sh arm64
      
    - name: Upload ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mimalloc-arm64
        path: mimalloc-binaries/arm64/
        retention-days: 1